title: The Hacker Witch | InfoSec Compendium
description: > # this means to ignore newlines until "baseurl:"
  The Hacker Witch is a compendium of information security knowledge authored by Victoria M. Galvan. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: thehackerwitch #if your site has a twitter account, enter it here

# Author Settings
author: The Hacker Witch # add your name
author-img: victoriamgalvan.jpg  # add your photo
about-author: Pen Tester in Training | Cat Mom | Mystical Being # add description
social-twitter: thehackerwitch # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: ch4kra # add your Github handle
social-linkedin: victoriamgalvan # add your Linkedin handle
#social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
